Updated directlineclient to use sockets, added logging and extended timeout to 3 mins
microsoft/BotFramework-FunctionalTests pull request #245
Opened 2021-01-22 22:36 UTC by gabog

Relates to #243
This PR includes: 
- Added TestRequestTimeout (set to 180 secs) in appsettings.json and updated TestRunner to take it as a parameter and use it.
- Added logger to DirectLinetTestClient and added debug messages to help us track failures.
- Updated appsettings log level to debug (for now) and fixed ScriptTestBase so it loads logging settings from appsettings.
- Excluded Python skills from ExpectReplies scenarios.
- Refactored DirectLineTestClient to use websockets instead of polling.
- Upated XUnit references in TranscriptTestRunner.csproj so VS doesn't think it is a unit test project

2021-01-23 18:33 UTC, gabog commented
Found some issues, converting it to draft until I figure them out (any feedback is welcomed anyway)

2021-01-24 21:38 UTC, gabog commented
@denscollo / @ceciliaavila, this branch is ready to merge, can you try it out with the pipeline and see if the timeout issues improve? 

Using azure app restart for testing may give weird results because the restarts are not immediate and may come in the middle of a test, so try it with the pipeline and let me know how it goes. 

Take a look at the code and let me know if you see anything strange but the changes to the DirectLineTestClient are pretty complex, we can jump on a call and I can explain what I did if you need more details. 

Thanks

2021-01-25 16:53 UTC, ceciliaavila requested changes
Just some details:
- Commented line in AppSettings.json.
- Missing update of the `EchoComposerTests` class to include the new arguments in the XUnitTestRunner instantiation and the rename of the _testScriptsFolder folder.

2021-01-25 17:06 UTC, gabog commented on Tests/SkillFunctionalTests/appsettings.json
> +  // Test request timeout (in seconds)
Done, thanks!

2021-01-25 17:10 UTC, ceciliaavila approved these changes

2021-01-25 17:15 UTC, merged